apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /rest
        backend:
          serviceName: rest-app-service
          servicePort: 80
      - path: /graphql
        backend:
          serviceName: graphql-app-service
          servicePort: 4000                  
      - path: /soap
        backend:
          serviceName: soap-app-service
          servicePort: 8080
                
      