apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: graphql-app
  labels:
    visualize: "true"    
spec:
  selector:
    matchLabels:
      app: graphql-app
  replicas: 1
  template:
    metadata:
      labels:
        app: graphql-app
        visualize: "true"
    spec:
      containers:
      - name: graphql-app
        image: mariohercules/nodejs:1.0.2-wspy3.6
        env:
         - name: NODE_MODE
           value: "graphql"
        ports:
        - containerPort: 4000