apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rest-app
  labels:
    visualize: "true"   
spec:
  selector:
    matchLabels:
      app: rest-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-app
        visualize: "true"
    spec:
      containers:
      - name: rest-app
        image: mariohercules/nodejs:1.0.6-wspy3.6
        env:
         - name: NODE_MODE
           value: "rest"
        ports:
        - containerPort: 4000
