apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: soap-app
  labels:
    visualize: "true"    
spec:
  selector:
    matchLabels:
      app: soap-app
  replicas: 1
  template:
    metadata:
      labels:
        app: soap-app
        visualize: "true"
    spec:
      containers:
      - name: soap-app
        image: mariohercules/nodejs:1.0.5-wspy3.6
        env:
         - name: NODE_MODE
           value: "soap"
        ports:
        - containerPort: 8001