apiVersion: v1
kind: Service
metadata:
  name: graphql-app-service
  labels:
    app: graphql-app
    visualize: "true"
spec:
  type: NodePort
  selector:
    app: graphql-app
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    name: http