apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
  labels:
    app: rest-app
    visualize: "true"
spec:
  selector:
    app: rest-app
  ports:
  - port: 4000
    targetPort: 4000
    name: rest-app-web-ui
    