apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
  labels:
    app: rest-app
    visualize: "true"
spec:
  type: NodePort
  selector:
    app: rest-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
    