apiVersion: v1
kind: Service
metadata:
  name: soap-app-service
  labels:
    app: soap-app
    visualize: "true"
spec:
  selector:
    app: soap-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080